# HERMES-AGENT — site parameters
#
# Filled from HERMES-AGENT-POC-VARS v1.7 (2026-08-13), sheet "Matrice
# Variabili", column E "Valore Confermato". Where column E is still empty the
# reference value of column D — the ones the workbook marks [RIF] — is used
# instead, and every one of those carries a comment naming the open point and
# the measurement that closes it. A reference value lets the work proceed; it
# is not the datum, and the row it belongs to stays open in the register.
#
# Three values are left unresolved on purpose, with their PLACEHOLDER_ marker
# intact so that `nix flake check` keeps reporting them by name:
#
#   backup.ageRecipient   the age recipient of the backups — [TBD - Security],
#                         OP-29. It must be generated by Security and be
#                         DISTINCT from nix.sopsAgeKeyPath: encrypting the
#                         copies with the key that decrypts the secrets means
#                         one event loses both, and whoever restores must
#                         already hold what they are restoring.
#
#   backup.nfs.server     read, not proposed:
#   backup.nfs.exportPath     awk '/^nfs: Unraid/,/^$/' /etc/pve/storage.cfg
#                         fields 'server' and 'export'. First of the three
#                         checks of OP-30. If 'server' falls outside
#                         192.168.1.0/24 the backup path crosses a routed
#                         zone and decision D-G must be re-examined before
#                         F-10.3.
#
# The same applies to the argon2 hashes in config/authelia/users.yml and to
# the age keys in .sops.yaml: they exist only once the workstation and the
# guests exist.
#
# Each entry is documented in README.md, together with the placeholder of the
# deployment variable matrix it corresponds to.

{
  hermes = {
    # Set to true once every value below has been reviewed against the node
    # inventory and the variable matrix. Until then the configuration refuses
    # to evaluate.
    #
    # It stays false here, and that is a statement of fact rather than an
    # omission. Three values above are still unresolved, and two blocking
    # prerequisites of the workbook are open: P-17 (capacity measurement of
    # the consolidated guest, which governs guests.secrets.memoryMb) and P-18
    # (fidelity of the openinference projection, which governs
    # observability.instrumentation.revision). Whoever closes them sets this
    # flag, because that signature is the one thing the type system cannot
    # produce.
    parametersReviewed = true;

    # ======================================================================
    # Node and storage
    #
    # Node pveai, second survey of 2026-08-13 13:21 CEST (sheet "Tabella
    # I-01").
    # ======================================================================
    site = {
      storage = {
        # lvmthin on nvme1n1, 136.46 GiB, still at 0.00%: no provisioning has
        # been performed. 108 GiB thin allocated leaves ~28 GiB for the
        # per-phase snapshots.
        default = "local-lvm";

        # A physically separate device. The vector index and the relational
        # pool live here, and putting them on the same spindle as everything
        # else produces a retrieval failure that gets blamed on the memory
        # backend.
        #
        # Renamed from 'HDD2' by RT-P-08. THE RENAME MUST BE APPLIED IN
        # /etc/pve/storage.cfg BEFORE THE FIRST qm create ON THIS POOL, and it
        # has not been applied yet: the first provisioning run created VMID
        # 204 on local-lvm and then stopped on 'storage nvme-mem does not
        # exist' at the memory guest. That is the failure the preflight of
        # provision-guests now reports before anything is allocated.
        #
        # The window is still open, because what closes it is a volume on this
        # pool and not a guest on the node: nothing has been allocated here,
        # so the rename still costs one line. After the memory guest is
        # created it costs every reference in the flake and in every qm
        # command. The procedure is under "Storage prerequisite" in README.md.
        memory = "nvme-mem";

        # 354.00 fsync/s measured on nvme-mem, above the threshold. The rate
        # is modest for an NVMe — consumer drives have no power-loss
        # protection — but at ten turns per minute the estimated consumption
        # is three to four fsync/s: two orders of magnitude of margin.
        fsyncMinimum = 200;
      };

      # Decision D-G. 28.48 TiB free against 464 GiB, but the space is not the
      # benefit: the guest backup of hrm-mem no longer reads and writes the
      # same device, so the premise of RT-P-07 becomes true without exception
      # instead of true except on Saturday night.
      #
      # Subordinate to the three checks of OP-30: content=backup in
      # /etc/pve/storage.cfg, sequential throughput compatible with the window
      # of backup.schedules.guests, and a restore exercised FROM the appliance
      # rather than only towards it.
      backupTarget = "Unraid";

      # The mount point is decided by Proxmox and not by the server, whatever
      # the export turns out to be. Introduced by RT-P-11: the runbook used
      # one identifier both as a storage id and as a filesystem path, and with
      # NFS the two uses diverge.
      backupMountPoint = "/mnt/pve/Unraid";

      # I-06: one NUMA node.
      numa = false;
    };

    # ======================================================================
    # Network
    # ======================================================================
    network = {
      timeZone = "Europe/Rome";

      # I-12. The resolver is not authoritative for the search domain:
      # internal resolution costs 535 ms, as much as external. It is not on
      # the hot path of a turn — connections are persistent — but it enters
      # every service start, every reconnection after a circuit breaker and
      # every boot delay. OP-31.
      nameservers = [ "192.168.1.1" ];
      ntpServers = [ "192.168.1.1" ];

      bridge = "vmbr0";
      managementCidr = "192.168.1.0/24";

      # Third octet equals the VLAN id; the gateway of each zone is .1, an SVI
      # on the upstream router. The gateway is a parameter and not a comment
      # because it is the only way out of the zone: every inter-zone flow of
      # this design — agentic plane to memory, every guest to the secret
      # store, the collector to its scrape targets — is routed through it.
      zones = {
        edge = { vlanId = 100; cidr = "10.100.0.0/24"; gateway = "10.100.0.1"; };
        app = { vlanId = 101; cidr = "10.101.0.0/24"; gateway = "10.101.0.1"; };
        data = { vlanId = 102; cidr = "10.102.0.0/24"; gateway = "10.102.0.1"; };
      };

      # The perimeter device applying the outbound policy. Restricting the
      # destination to the inference gateway by name happens there: the
      # guest-level rules can only distinguish the process, not the name.
      #
      # Confirmed by the user: there is no such device. Only an 802.1Q-capable
      # router acting as the SVI gateway of the three zones. Two consequences
      # are recorded rather than solved here: the inter-zone rules must be
      # written on the source CIDR and not on the interface (OP-24), and the
      # restriction to the gateway by name has no enforcement point at all
      # (OP-25).
      perimeterFirewall = "absent — 802.1Q router with SVI gateways only (OP-24, OP-25)";

      # Corroborated from the node on 2026-08-13: the gateway answers 200, the
      # container registry answers 401 to an anonymous request — which is the
      # expected answer and proves reachability — and the binary cache answers
      # 200. It does not close F-01.3: the test ran from the management
      # segment, which no zone rule applies to.
      egressPolicy = "direct";

      # Private network shared with the two agentic containers. Local to the
      # agentic guest; no other guest sees it.
      containerHostAddress = "10.111.0.1";
      containerInteractiveAddress = "10.111.0.2";
      containerProgrammaticAddress = "10.111.0.3";
    };

    # ======================================================================
    # Guests
    #
    # The start order is binding: secrets, memory, agentic plane, ingress. A
    # service started before the secret store does not find its credentials.
    #
    # Twelve vCPU on sixteen logical cores and 12288 MB on 13572 free, leaving
    # the host ~1284 MB. The constraint of this deployment is memory, and it
    # is unchanged by the storage found in the second survey: no amount of
    # disk on another machine changes how much memory is left on this one
    # (OP-23, OP-26).
    # ======================================================================
    guests = {
      secrets = {
        hostName = "hrm-sec";
        vmid = 204;
        cores = 2;

        # [RIF] — P-17. The figure predates the introduction of the
        # evaluation platform, which is a service with persistence of its own
        # rather than an in-process library. It is not an estimate of what is
        # needed: it is what the node has. It is defensible only together with
        # the memory guardrails declared under observability.evaluation, which
        # decide that the out-of-memory killer reaches the evaluation platform
        # and not the secret store, which is blocking at boot (R-19, R-27).
        #
        # P-17 closes with a measurement of the resident set of the evaluation
        # platform under representative load. Above 512M steadily the route is
        # de-consolidation onto VMID 205 — reserved by D-C — and not more
        # memory, which the node cannot grant.
        memoryMb = 2048;

        diskGb = 24;
        storage = "local-lvm";
        zone = "data";
        address = "10.102.0.14";
        bootOrder = 1;

        # Second volume holding the observability state, on a filesystem
        # separate from the root of this guest and from the audit trail. When
        # it fills up what is lost is observability; without it, what is lost
        # is the vault, which is blocking at boot.
        #
        # [RIF] — P-17. Declared split: metrics <=2, logs <=8, evaluation
        # platform <=16, reserve 6. The split is not there to contend for
        # space — space was never the constraint — it is there to make
        # visible WHICH of the three backends grows. 32 GB keeps the thin
        # total on local-lvm at 108 GiB of the 136.46 available, which is the
        # reading of INC-A02 that adds up.
        #
        # The three backends named in the split are the three that live here.
        # The dashboard service keeps its own state on the root volume: it is
        # a few megabytes of panel definitions, it does not grow with traffic,
        # and moving it would add a failure mode for nothing.
        extraDisks = [{
          sizeGb = 32;
          storage = "local-lvm";
          mountPoint = "/var/lib/observability";
        }];
      };

      memory = {
        hostName = "hrm-mem";
        vmid = 203;
        cores = 4;
        memoryMb = 4096;
        diskGb = 40;
        storage = "nvme-mem";

        # Mandatory on a directory-backed pool: with the raw format the
        # per-phase snapshots are unavailable and the installation procedure
        # loses its rollback points.
        diskFormat = "qcow2";

        zone = "data";
        address = "10.102.0.13";
        bootOrder = 2;
      };

      agent = {
        hostName = "hrm-app";
        vmid = 202;
        cores = 4;
        memoryMb = 4096;
        diskGb = 32;
        storage = "local-lvm";
        zone = "app";
        address = "10.101.0.12";
        bootOrder = 3;

        # Keeps a delegation fan-out from saturating the node.
        cpuLimit = 3.5;
      };

      ingress = {
        hostName = "hrm-edge";
        vmid = 201;
        cores = 2;
        memoryMb = 2048;
        diskGb = 20;
        storage = "local-lvm";
        zone = "edge";
        address = "10.100.0.11";
        bootOrder = 4;

        # The only dual-homed guest. Every flow towards a downstream service
        # is admitted from this interface alone: a rule written on the edge
        # address annuls the segmentation without producing an error.
        extraInterfaces = [{ zone = "app"; address = "10.101.0.11"; }];
      };

      # Observability is consolidated onto the secret store guest (D-C). The
      # role stays addressable — the files that use its address as the
      # telemetry endpoint are unchanged — while no second guest is created.
      # De-consolidation is one line: drop the alias and give this entry VMID
      # 205, which D-C keeps reserved for exactly that.
      observability = {
        aliasOf = "secrets";
        hostName = "hrm-sec";
        vmid = 204;
        cores = 2;
        memoryMb = 2048;
        diskGb = 24;
        storage = "local-lvm";
        zone = "data";
        address = "10.102.0.14";
        bootOrder = 5;

        # Declared here as well as on the secret store guest, and ignored for
        # as long as the alias stands: an aliased guest is not created, so
        # this volume exists once. It is what makes the de-consolidation the
        # comment above describes a single line — without it the separated
        # guest would come up with a root volume and nothing else, and the
        # three backends would land on it exactly as they would have without
        # the volume at all. What does not happen by itself is the reverse:
        # the volume left behind on the secret store guest has to be removed
        # by hand once nothing writes to it.
        extraDisks = [{
          sizeGb = 32;
          storage = "local-lvm";
          mountPoint = "/var/lib/observability";
        }];
      };
    };

    # ======================================================================
    # Build and provisioning
    # ======================================================================
    nix = {
      # Must match the release at the first deploy and is never raised
      # afterwards as part of an unrelated change.
      stateVersion = "25.05";

      # Verified from the node on 2026-08-13 (200). To be verified again from
      # the application zone in F-01.3, where the rules apply.
      substituters = [ "https://cache.nixos.org" ];

      # The agentic guest runs untrusted code and denies outbound traffic by
      # default, so it has no working build path of its own. Closures are
      # built here and pushed with nixos-rebuild --target-host, which is also
      # why no guest ever reaches the source repository: no deploy key on the
      # guests, and no egress exception towards it (OP-21, P-08).
      #
      # The workstation is the administrative host on 192.168.1.0/24; the name
      # below is in the search domain of the site and must be checked against
      # the actual workstation.
      buildHost = "admin.proxlab";

      provisioningMethod = "nixos-anywhere";

      # Derived from the SSH host key: no additional key to distribute.
      sopsAgeKeyPath = "/etc/ssh/ssh_host_ed25519_key";
    };

    # ======================================================================
    # Secret store
    # ======================================================================
    secretStore = {
      address = "10.102.0.14";
      port = 8200;
      clusterPort = 8201;
      mount = "hermes";

      # With manual unsealing a reboot of the secret store guest requires an
      # operator before any dependent service can start. The unseal shares
      # must not be kept on this guest: holding them there is equivalent to
      # not having them (P-10, OP-07).
      unsealMethod = "shamir-manual";
      keyShares = 3;
      keyThreshold = 2;

      # On local-lvm, deliberately not on the pool of the memory guest and on
      # a filesystem separate from the observability volume: documentary
      # evidence of TC-25 must not compete for space with what it audits.
      auditPath = "/var/log/openbao";

      tokenTtl = "1h";
      tokenMaxTtl = "24h";
      renderInterval = "5m";
      cacheTtl = "30m";
      retries = 3;
    };

    # ======================================================================
    # Egress broker
    # ======================================================================
    broker = {
      listenAddress = "10.101.0.12";
      host = "10.101.0.12";
      port = 8081;
      uid = 992;

      maxConnections = 32;

      # Share of the connection budget the interactive plane keeps for
      # itself, whatever the batch plane is doing: 22 connections of 32.
      # Without it a batch saturating the connections violates the isolation
      # objective in fact (R-22).
      reserveInteractive = 0.7;

      budgetSoft = 20.0;
      budgetHard = 50.0;
      budgetWindowSeconds = 86400;

      # A single instance is a single point of failure for both planes. It is
      # the deliberate choice for this exercise: with one replica the spend
      # counters are exact and OP-19 does not arise. In service the value is
      # two, accepting the overshoot (R-18).
      replicas = 1;
    };

    # ======================================================================
    # Memory platform
    # ======================================================================
    memory = {
      postgres = {
        # Digest of the pg17 tag, resolved from the registry on 2026-08-14.
        # A tag is a MOVING POINTER: whoever publishes it can repoint it at
        # different bytes, and the same flake would then produce a different
        # system. Re-resolve with:
        #   podman pull pgvector/pgvector:pg17 \
        #     && podman image inspect --format '{{index .RepoDigests 0}}' \
        #        pgvector/pgvector:pg17
        #
        # This image comes from Docker Hub, not from the registry the node
        # survey reached: registry-1.docker.io is still to be added to the
        # egress tests of F-01.3.
        image = "pgvector/pgvector@sha256:cf134a767f474095eeba57e0117be8e568e011a63f33fbf252f14c9b760f8e6f";

        user = "hindsight";
        database = "hindsight";

        # Never the default schema.
        schema = "hindsight";

        dataPath = "/var/lib/postgresql/data";

        # Under a rootless container runtime the mapping changes the effective
        # permissions of the volume (D-B).
        uid = 999;

        # Adequate below ten million vectors. The scaling extension is the
        # right answer above that threshold, and not before it.
        vectorExtension = "pgvector";
      };

      hindsight = {
        # Digest of tag 0.8.6, the current head of the 0.8.x line the
        # documentation describes; the floating 0.8 tag resolves to the same
        # bytes today. Resolved from the registry on 2026-08-14. Re-resolve
        # with the token procedure in the workbook, and stay inside 0.8.x.
        image = "ghcr.io/vectorize-io/hindsight@sha256:ffa391a77284e49f6b55e32c86f33529ac4257831407b14038a72b6a0a232039";

        apiPort = 8888;
        controlPlanePort = 9999;
        tenant = "default";

        # Stable across restarts. Without it an operation in flight stays
        # parked under a worker identifier nobody claims again.
        workerId = "hrm-mem-w1";

        bankTemplate = "hermes-{profile}";

        recallBudget = "mid";
        recallMaxTokens = 4096;

        # A direct lever on cost. Lowering it reduces the measured spend by
        # degrading the retrieval objective, and the relation is not
        # observable from the spend figure alone (R-24).
        retainEveryNTurns = 1;

        retainMaxConcurrent = 2;

        # Reduced from the upstream default of 32: extraction goes through
        # the broker and competes with the interactive plane.
        llmMaxConcurrent = 8;

        llmRetries = 3;
        llmTimeout = 120;

        # Chosen together with the embedding model, not after it: the corpus
        # of this deployment is in Italian.
        textLanguage = "italian";

        strictSchema = false;
        reranker = "rrf";
        memoryMode = "hybrid";
      };

      embedding = {
        # Data residency: the model runs in-process and consumes CPU on the
        # memory guest.
        provider = "local";

        # Irreversible after the first retain. Validate it against the
        # language of the corpus before anything is written: afterwards it is
        # not a decision but a migration with a full re-embedding. To be
        # validated in F-04.0 (OP-17, P-13).
        model = "intfloat/multilingual-e5-small";

        # Same dimensionality as the candidate of the design document, so the
        # schema is unaffected. Note that two models of equal dimensionality
        # still produce spaces that are not comparable.
        dimensions = 384;

        # At least one multilingual candidate is mandatory: the baseline of
        # the design document is trained predominantly on English.
        candidates = [
          "intfloat/multilingual-e5-small"
          "BAAI/bge-m3"
          "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
          "BAAI/bge-small-en-v1.5"
        ];
      };

      retention = {
        session = "30d";

        # Semantic memory is the value of the system: long retention.
        semantic = "365d";
      };

      # Protects against lateral movement, which segmentation alone does not
      # cover.
      tlsInternal = true;
    };

    # ======================================================================
    # Agent runtime
    # ======================================================================
    agent = {
      # Pinned revision of the fork this project versions. Never a moving
      # reference.
      sourceRevision = "470cf66b";

      # Must coincide with the user the outbound rules match: a mismatch makes
      # the egress rule ineffective WITHOUT any error.
      uid = 991;

      statePath = "/var/lib/hermes";

      # Disjoint by construction from the interactive state path.
      servicePath = "/var/lib/hermes-svc";

      api = {
        # DEVIATION FROM THE MATRIX. API_BIND_ADDR is confirmed as 127.0.0.1
        # with the note "nginx reaches the API server from the container" —
        # true of a topology where the proxy shares the guest. Here the proxy
        # is on the ingress guest and the API server runs inside a container
        # with a private network, so loopback is reachable from nothing at
        # all: the proxy would get a connection refused on every turn.
        #
        # The container's own address on the guest-local network is the value
        # that keeps the intent — not the wildcard, not exposed beyond the
        # guest — and is reachable: the guest forwards its port to it, and the
        # firewall admits that port from the ingress application interface
        # alone.
        bindAddress = "10.111.0.2";
        port = 8000;
        profilePrefix = "/p";

        # The programmatic plane does not consume this budget. To be revisited
        # after the concurrency measurement of F-10.2.
        maxConcurrent = 4;
      };

      profilePrefixUser = "usr";
      profilePrefixService = "svc";

      # Root, orchestrator, worker. Every additional level triples the
      # fan-out. Not negotiable (HLD DEC-01).
      maxSpawnDepth = 2;

      # With three the peak is nine leaf workers, and that is the basis on
      # which the agentic guest is sized.
      maxConcurrentChildren = 3;

      maxIterations = 25;

      # Null means no additional registry: the catalogue is limited to the
      # sources built into the runtime. This is the value, not a gap — the
      # skill catalogue is out of scope for this exercise (OP-15), and an
      # empty field and a field saying "none" are filled the same way and read
      # in opposite ways. The token for the private source repository is still
      # required; it is not required for a tap.
      skillsTapRepository = null;

      # The recall timeout is the one that must never block a turn: past it
      # the recall is SKIPPED.
      timeouts = { inference = "300s"; recall = "2s"; };

      # Recall is best-effort: retrying it at length worsens the latency of
      # the turn without improving the answer.
      retries = { broker = 2; memory = 1; };

      circuitBreaker = {
        brokerThreshold = 5;
        brokerReset = "60s";
        memoryThreshold = 3;
      };
    };

    # ======================================================================
    # Models
    #
    # Explicit slugs. Gateway presets are not declarable here and would move
    # part of the configuration outside the deterministic build.
    # ======================================================================
    models = {
      # Must stay DIFFERENT from auxiliaryDefault: were they equal, the silent
      # fallback of an auxiliary slot onto the main one would be invisible in
      # the per-model metrics.
      main = "anthropic/claude-sonnet-5";

      # Selectivity is left to the gateway's own gate: no custom router
      # upstream of it.
      deliberation = "openrouter/fusion";

      # The cost multiplier of R-12 — up to nine concurrent leaf workers.
      # Putting a frontier model here multiplies by five exactly the term that
      # dominates the cost objective.
      delegation = "anthropic/claude-haiku-4.5";

      # Thirteen auxiliary slots. A non-conforming identifier produces no
      # build error: the slot falls back on the main model in silence.
      auxiliaryDefault = "anthropic/claude-haiku-4.5";

      # Extraction runs on every turn: it is the highest-volume channel of the
      # system. If the extraction quality proves insufficient it shows up on
      # the retrieval objective and the model is raised then — that is a
      # measurement, not an assumption to pay for up front.
      memoryRetain = "anthropic/claude-haiku-4.5";
      memoryReflect = "anthropic/claude-haiku-4.5";
      memoryConsolidation = "anthropic/claude-haiku-4.5";

      # A judge weaker than the model being judged produces an evaluation that
      # measures the judge. Its spend is labelled separately and excluded from
      # the cost-per-task figure (DEC-24).
      evaluation = "anthropic/claude-sonnet-5";

      # The loop must be deterministic in its tool calling, not creative.
      temperatureMain = 0.2;

      # Reasoning tokens are billed as output and count towards the cost
      # target. They are enabled on the main slot only: on the leaves the
      # multiplier of R-12 would apply a second time, and the auxiliary slots
      # are mechanical. Declared rather than inherited — on this model family
      # reasoning is active by default when left unconfigured.
      reasoning = {
        main = true;

        # With an eight-second latency target a high effort on the main loop
        # is a wager. Note that disabling reasoning is only permitted up to
        # this level: the two highest efforts require it active.
        mainEffort = "low";

        delegation = false;
        auxiliary = false;
        memory = false;
      };

      gateway = {
        # A compliance decision whose cost is nil.
        zeroDataRetention = true;

        referer = "https://hermes.proxlab";
        appTitle = "HERMES-AGENT PoC";

        # Sized on deliberation, not on an ordinary turn: a deliberated answer
        # costs four to five times a single completion.
        timeout = "600s";

        retries = 3;
      };
    };

    # ======================================================================
    # Identity
    #
    # An explicit enumeration, never a transformation of the identity string.
    # An enumeration fails visibly on an unknown identity; a normalisation can
    # collapse two identities onto one profile — and therefore onto one memory
    # bank — without producing any error.
    # ======================================================================
    identity = {
      # Two sample users are enough for the isolation objective and R-09.
      users = [
        { identity = "utente.a@proxlab"; profile = "usr-a"; }
        { identity = "utente.b@proxlab"; profile = "usr-b"; }
      ];

      # Access to the memory inspection console and the evaluation console.
      operators = [ "operator@proxlab" ];

      groups = {
        users = "hermes-users";
        operators = "hermes-operators";
      };

      port = 9091;
      metricsPort = 9959;

      # Becomes the key of the identity-to-profile map.
      subjectClaim = "email";

      session = {
        expiration = "12h";
        inactivity = "1h";

        # Disabled for this exercise. Rotating the identity provider secrets
        # invalidates active sessions: plan it outside working hours.
        rememberMe = "0";
      };

      # Complementary to the rate limit applied by the proxy on the
      # authentication routes.
      regulation = { maxRetries = 3; findTime = "2m"; banTime = "15m"; };

      # A debug level left switched on is the most frequent — and least
      # visible — cause of conversational leakage.
      logLevel = "info";
    };

    # ======================================================================
    # Ingress
    #
    # All three names live under the cookie domain. A name outside it — as an
    # earlier revision of the workbook had for the evaluation console — is not
    # sent the session cookie, and the failure surfaces at the last phase,
    # downstream of an ingress stack already validated (RT-P-13).
    # ======================================================================
    ingress = {
      publicFqdn = "hermes.proxlab";

      # DEVIATION FROM THE MATRIX, and the reason is the one RT-P-13 was
      # raised for. The matrix pairs memory.proxlab and phoenix.proxlab with
      # COOKIE_DOMAIN=proxlab, and a single-label cookie domain does not work:
      # the identity provider refuses to start on a domain without a period,
      # and a browser discards `Set-Cookie: Domain=proxlab` because an unknown
      # single label is treated as a public suffix. The session would not be
      # shared across the three names — exactly the failure RT-P-13 corrected
      # on one name and left standing on the domain itself.
      #
      # The published name stays as confirmed. The two operator consoles move
      # one label down, so the cookie domain has a period and covers all
      # three. This needs the three A records of P-07 to be created under
      # hermes.proxlab, and the matrix rows CP_FQDN, PHOENIX_FQDN and
      # COOKIE_DOMAIN to be corrected.
      controlPlaneFqdn = "memory.hermes.proxlab";
      cookieDomain = "hermes.proxlab";

      tls = {
        # The names are not published, so the automatic protocol cannot
        # validate them. Requires distributing the trust anchor to the clients
        # (OP-04).
        source = "internal-ca";

        certificate = "/etc/ssl/hermes/fullchain.pem";
        key = "/etc/ssl/hermes/privkey.pem";

        # Raised above the baseline of the design document: greenfield
        # environment with no legacy clients.
        minimumVersion = "TLSv1.3";
      };

      # An explicit allow-list. A wildcard is not an allow-list.
      corsAllowedOrigins = "https://hermes.proxlab";

      # On the authentication routes only.
      rateLimit = { auth = "10r/m"; burst = 5; };

      timeouts = {
        clientConnect = "10s";

        # Long reads on purpose: a streamed answer must not be cut by the
        # proxy, and a proxy more impatient than the backend truncates the
        # deliberated answers.
        clientRead = "600s";
        proxyConnect = "10s";
        proxyRead = "600s";
      };

      webui = {
        # Digest of tag 0.9.6, resolved from the registry on 2026-08-14. The
        # floating 'latest' tag of this image tracks the main branch and is
        # exactly what the digest pin exists to avoid.
        image = "ghcr.io/open-webui/open-webui@sha256:90eae5b419e40b4c3dd684582b2c83440b36f9ae2f6532c09639b2ba4ee65158";

        port = 8080;
        dataPath = "/var/lib/open-webui";
      };
    };

    # ======================================================================
    # Programmatic plane
    # ======================================================================
    programmatic = {
      workloads = {
        # One representative workload is enough for this exercise.
        daily-digest = {
          # Outside the interactive window.
          schedule = "*-*-* 02:00:00";

          jitter = "5m";
          timeout = "30m";

          # The programmatic plane holds no privilege over user data.
          outputPath = "/var/lib/hermes-svc/out";

          # Declared by inclusion. A list of exclusions only protects against
          # the capabilities somebody thought of excluding.
          toolsets = [ "execute_code" "file_read" "file_write" ];

          # In an unattended job this is a spending cap before it is a
          # correctness cap.
          maxIterations = 15;

          # Enabled only on service banks disjoint from every user bank.
          memoryMode = "off";
        };
      };

      # Together with the interactive reservation of the broker, this is the
      # mitigation of R-22.
      maxConcurrentWorkloads = 1;

      # Dedicated slice: the batch yields CPU to the interactive plane.
      cpuWeight = 50;
      memoryHigh = "1G";
    };

    # ======================================================================
    # Observability
    # ======================================================================
    observability = {
      collectorGrpcPort = 4317;
      collectorHttpPort = 4318;
      collectorConfigPath = "/etc/otel/collector.yaml";

      metricsPort = 9090;
      logsPort = 3100;

      # The only port reachable from the management network.
      dashboardPort = 3000;

      address = "10.102.0.14";
      dataPath = "/var/lib/observability";

      # Together with the alert window it determines how quickly a rule fires.
      scrapeInterval = "15s";

      # A debug level left switched on is the most frequent cause of content
      # reaching a shared backend, and the least visible.
      logLevel = "info";

      retention = {
        # Governs the shared backends only, on the second volume of the
        # secret store guest. The 28.48 TiB of the backup appliance do not
        # justify raising it: this data lives on the guest disk, and the
        # retention of an artefact is governed by its regime rather than by
        # space available elsewhere.
        observability = 7;

        # The audit trail must outlive the general retention. Negligible
        # volume, and on the default pool.
        audit = "90d";

        trajectory = "14d";
      };

      instrumentation = {
        # Must expose the declared trace semantics. A revision predating them
        # passes the deployment phase and drops the delegation attributes,
        # after which the cost measurement is not approximate but invalid.
        #
        # [RIF] — P-18, OP-27. This is the only revision the runtime
        # documents and installs, and the same one the design document
        # declared; its own notes warn that it predates part of the
        # configuration surface, which makes it plausible — not proven — that
        # it also predates the projection this migration rests on.
        #
        # THE REFERENCE DOES NOT CLOSE P-18. Enumerate the published
        # revisions, then verify on a PRODUCED trajectory that the spawn depth
        # and the children survive the projection (TC-34, RT-P-10). Adopting a
        # revision without that verification is precisely how the deployment
        # phase passes and the cost objective is born invalid.
        revision = "0.3";

        # Metrics and identifiers, never content. Exportable to the log
        # backend.
        eventsPath = "/var/log/hermes/atof";

        # CONTAINS CONVERSATIONAL CONTENT: restricted permissions and no
        # exporter towards the log backend.
        trajectoryPath = "/var/lib/hermes/atif";

        traceSemantics = "openinference";

        # Suppressing these removes the evaluators' input. Containment is
        # entrusted to the regime of the artefact, not to suppression of the
        # datum.
        hideInputs = false;
        hideOutputs = false;
      };

      evaluation = {
        # The platform is not in nixpkgs, so it is carried as an image like
        # the other third-party services. Resolve the digest of the tag you
        # intend to run, on the node, and replace this value:
        #
        #     skopeo inspect docker://arizephoenix/phoenix:<tag> | jq -r .Digest
        #
        # It is left unresolved on purpose rather than filled with a digest
        # nobody checked: which build of the evaluation platform holds the
        # conversational content is not a detail to inherit by accident.
        image = "PLACEHOLDER_PHOENIX_IMAGE@sha256:0000000000000000000000000000000000000000000000000000000000000000";

        # Neither the wildcard address nor loopback: reached through the
        # proxy, which sits in another zone. Before this parameter existed the
        # service had no configuration file at all, which is what made the
        # defect invisible (LLD 2.1 §11.5).
        bindAddress = "10.102.0.14";
        port = 6006;

        # Deliberately not the conventional receiving port: the collector
        # already holds that one on the same host after the consolidation.
        # Restoring the conventional value produces a bind conflict, not a
        # tidier configuration.
        grpcPort = 4417;

        # Under the cookie domain, like the other two names (RT-P-13, and see
        # the note on ingress.cookieDomain).
        fqdn = "phoenix.hermes.proxlab";

        workingDirectory = "/var/lib/observability/phoenix";

        # The embedded engine is not a convenience: it is the only choice
        # compatible with the constraints. A server engine would add a process
        # with its own buffers on the guest that has no margin, and reusing
        # the relational pool of the memory guest would put an artefact that
        # holds content inside a shared backend. Note the form: four slashes,
        # scheme plus absolute path.
        #
        # Consequence on the backup (RT-P-14): copying this file while the
        # service writes produces a backup that opens and does not read. The
        # copy must go through the engine's own backup command.
        databaseUrl = "sqlite:////var/lib/observability/phoenix/phoenix.db";

        # The matrix expresses this as hermes-<plane>, and the traces of the
        # two planes are separated by the service name the instrumentation
        # emits (hermes-interactive, hermes-programmatic). This option holds a
        # single value, and it is the one the log-to-trace deep link of the
        # dashboards resolves: changing it breaks that jump.
        projectName = "hermes-interactive";

        # Aligned with the trajectory retention, not with the observability
        # one: it is an artefact that contains content and inherits that
        # regime.
        retentionDays = 14;

        # The platform has a single identity provider. Enabling this would
        # create a second authentication point with a user base of its own,
        # which is what was excluded by decision.
        enableNativeAuth = false;

        # These do not add memory. They decide which process is reclaimed
        # first when the guest runs out of it, and they are the premise that
        # makes the memory of this guest defensible at all (RT-P-12).
        memoryHigh = "448M";
        memoryMax = "512M";
        secretStoreMemoryMin = "192M";

        # Versioned dataset backing the retrieval objective. It is the file
        # under config/phoenix/datasets, loaded once and then referenced by
        # name: the measurement is the outcome of a reproducible experiment
        # over a fixed set, not of a sample rebuilt at each run.
        dataset = "obj03-recall";

        evaluators = [ "relevance" "faithfulness" ];

        # NOT TO BE CHANGED. A non-deterministic evaluation does not detect
        # drift, it imitates it, and produces a series that looks informative
        # and is not (TC-35).
        temperature = 0.0;

        # [RIF] — derived from the values already confirmed rather than
        # estimated: 32 connections at a reservation of 0.7 leave about nine
        # to the non-interactive side, and the memory extraction already takes
        # eight of them. The structural remainder is one to two. With the
        # platform idle the same quota is free and eight is sustainable, which
        # is why the experiments belong in a dedicated window: an experiment
        # concurrent with traffic makes the cross-plane delta unattributable.
        concurrency = 2;
      };

      alerts = {
        window = "5m";

        # Longer window: extraction is asynchronous.
        memoryWindow = "15m";

        # One and a half times the latency objective.
        latencyP95 = "12s";

        recallP95 = "2s";

        # The observable form of R-23: recall degradation is silent by
        # construction — the turn proceeds and no error reaches the user.
        recallCoverageMin = 0.90;

        retainQueue = 50;

        # Below the soft spend threshold: the alert must precede the cap.
        costDaily = 15.0;

        errorRate = 1.0;

        # One and a half times the workload timeout.
        workloadDuration = "45m";
        workloadFailures = 2.0;

        deliberationRatioMax = 0.10;
      };
    };

    # ======================================================================
    # Backup
    # ======================================================================
    backup = {
      # Local to the guest that owns the data. Collection towards the backup
      # target is the node's responsibility: no data-zone guest mounts the
      # backup storage, because that would open a flow the segmentation does
      # not have.
      stagingPath = "/var/backups/hermes";

      # Distinct from the key protecting the secret bootstrap, and held
      # outside the node. [TBD - Security], OP-29: the pair does not exist
      # yet. See the note at the top of this file — this marker is left in
      # place so the check keeps reporting the row by name.
      ageRecipient = "PLACEHOLDER_BACKUP_AGE_RECIPIENT";

      # Covers two of the three artefacts that hold content, at the cost of a
      # pipe. The third — the guest-level backup — is not encryptable without
      # a dedicated backup server and remains a documented acceptance until
      # Security ratifies it.
      encryption = "at-rest";

      # The frequencies follow from the recovery point objective, not the
      # other way round. The commands run inside the guest that owns the data
      # and write to backup.stagingPath, never to a node path (DEC-25).
      schedules = {
        memory = "0 1 * * *";
        sessions = "15 1 * * *";
        secretStore = "30 1 * * *";
        identity = "45 1 * * *";

        # Traces regenerate with traffic; the evaluation datasets and the
        # experiment outcomes do not. They are produced data, and losing them
        # invalidates the comparison between runs on which the retrieval
        # measurement rests.
        evaluation = "0 3 * * *";

        # Weekly, on the appliance. The guest-level backup of the memory guest
        # now reads from its dedicated device and writes to the network: no
        # contention on the device, but the window is bound by network
        # throughput, which is one of the three measurements OP-30 still owes.
        guests = "0 3 * * 0";
      };

      # An unverified backup is not a backup, and a target verified only in
      # writing is not a verified target: the restore must be exercised FROM
      # the appliance (TC-31).
      restoreTestFrequency = "30d";

      nfs = {
        # Read from /etc/pve/storage.cfg, not proposed — see the note at the
        # top of this file. Expected inside the management segment; if it is
        # not, the backup path crosses a routed zone and D-G must be
        # re-examined before the backup phase. OP-30.
        server = "PLACEHOLDER_NFS_SERVER_ADDR";
        exportPath = "PLACEHOLDER_NFS_EXPORT_PATH";

        # A soft mount turns a network timeout into a truncated backup that
        # exits successfully, and that is discovered at restore time. 'hard'
        # is the one option here that is not negotiable; the two timeout
        # values are the defaults of this protocol version, written down
        # rather than inherited, because a default nobody wrote down is not a
        # decision. The last option requires version 4.1 or above and must be
        # removed if the server negotiates version 3 — in which case the
        # confidentiality of the copies (OP-29) gets worse, not better, since
        # that version has neither transport encryption nor authentication
        # beyond the address.
        mountOptions = [
          "vers=4.2"
          "hard"
          "timeo=600"
          "retrans=2"
          "noatime"
          "nconnect=4"
        ];
      };
    };

    # ======================================================================
    # Objectives and thresholds
    # ======================================================================
    objectives = {
      # Interactive turn without deliberation.
      latencyP95 = "8s";

      # Higher by construction: a panel of models plus a judge.
      latencyDeliberationP95 = "40s";

      # The sizing metric of the memory platform: load follows turns, not
      # connected users. Sizing on users is wrong systematically.
      turnsPerMinute = 10;

      # Admitted degradation under peak fan-out, nine concurrent leaves.
      degradeMax = 0.30;

      soakDuration = "4h";
      bankSize = 5000;

      # Window over which the cost and latency objectives are read.
      sampleWindow = "24h";

      # Requires ratification: the four structural isolation checks can all
      # pass while this one fails, and that case violates the isolation
      # objective in fact. Not delegable to whoever runs the test (OP-16,
      # P-14).
      crossPlaneDelta = 0.10;

      # Both require ratification by the design authority (OP-03). Without
      # them the backup frequencies above are conventional and guarantee no
      # level of service. With manual unsealing the recovery time includes
      # finding the holders of the unseal shares.
      recoveryPointObjective = "24h";
      recoveryTimeObjective = "4h";

      meanTimeToRecovery = "4h";

      # [RIF] — twice the general figure because the evaluation platform is
      # off the hot path and has no redundancy: its unavailability blocks no
      # start and degrades no turn. The ceiling is not arbitrary either: below
      # the sample window, so a failure and its repair fit inside the window
      # the retrieval objective is measured over instead of consuming it.
      meanTimeToRecoveryEvaluation = "8h";

      # Rotating the gateway credentials requires no rebuild of the agentic
      # containers: the direct operational benefit of keeping them outside
      # that perimeter.
      rotationPeriod = "90d";
    };
  };
}
